config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: { sessions: 'sessions' }, skip: [:registrations, :passwords]
  root to: 'home#index'
  resources :home, only: [:index]
  resources :products
  resources :product_categories
  resources :product_images
  resources :customers
  resources :orders
  resources :order_items
  resources :admins do
    member do
      get :edit_password
      post :update_password
    end
  end

  get '*path' => redirect('/')
end

app/models/admin.rb
# == Schema Information
#
# Table name: admins
#
#  id                     :integer          not null, primary key
#  email                  :string(191)      default(""), not null
#  encrypted_password     :string(191)      default(""), not null
#  reset_password_token   :string(191)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(191)
#  last_sign_in_ip        :string(191)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
# == Schema Information
#
# Table name: customers
#
#  id         :integer          not null, primary key
#  nickname   :string(191)
#  mobile     :string(191)
#  password   :string(191)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Customer < ApplicationRecord
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id         :integer          not null, primary key
#  userId     :string(191)
#  amount     :string(191)
#  createdate :string(191)
#  paydata    :string(191)
#  canceldata :string(191)
#  province   :string(191)
#  city       :string(191)
#  county     :string(191)
#  address    :string(191)
#  name       :string(191)
#  phone      :string(191)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Order < ApplicationRecord
end

app/models/order_item.rb
# == Schema Information
#
# Table name: order_items
#
#  id              :integer          not null, primary key
#  orderId         :string(191)
#  productId       :string(191)
#  productName     :string(191)
#  productQuantity :string(191)
#  productprice    :string(191)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class OrderItem < ApplicationRecord
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id                  :integer          not null, primary key
#  name                :string(191)
#  originprice         :string(191)
#  price               :string(191)
#  description         :string(191)
#  quantity            :string(191)
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  product_category_id :integer
#

class Product < ApplicationRecord
  belongs_to :product_category
  has_many :product_images
  accepts_nested_attributes_for :product_images, :allow_destroy => true
end

app/models/product_category.rb
# == Schema Information
#
# Table name: product_categories
#
#  id         :integer          not null, primary key
#  name       :string(191)
#  comment    :string(191)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class ProductCategory < ApplicationRecord
  has_many :products
end

app/models/product_image.rb
# == Schema Information
#
# Table name: product_images
#
#  id         :integer          not null, primary key
#  product_id :string(191)
#  file       :string(191)
#  position   :string(191)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class ProductImage < ApplicationRecord
  mount_uploader :file, ProductImageUploader
  belongs_to :product
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
    @admins = Admin.all
    @admins = @admins.order('id desc').page(params[:page]).per(10)
  end

  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(admin_params)
    @admin.sign_in_count = 0
    if @admin.save
      redirect_to admins_path
    else
      render :new
    end
  end

  def edit
    @admin = Admin.find(params[:id])
  end

  def update
    @admin = Admin.find(params[:id])
    if @admin.update(admin_params)
      redirect_to admins_path
    else
      render :edit
    end
  end

  def edit_password
    # if current_admin.role == 'admin'
      @admin = Admin.find(params[:id])
    # else
    #   @admin = Admin.find(current_admin.id)
    # end
  end

  def update_password
    # if current_admin.role == 'admin'
      @admin = Admin.find(params[:id])
    # else
    #   @admin = Admin.find(current_admin.id)
    # end
    if @admin.update_attributes(admin_params)
      redirect_to params[:return_url].present? ? params[:return_url] : admins_path
    else
      render :edit_password
    end
  end

  private
  def admin_params
    params.require(:admin).permit!
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  protect_from_forgery with: :exception
  def index
    @product = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(products_params)
    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(products_params)
      redirect_to @product
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
    def products_params
      params.require(:product).permit(:name, :originprice, :price, :description, :quantity, :product_category_id, product_images_attributes: [:id, :file, :_destroy])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  layout 'login'
  private
  def respond_to_on_destroy
    redirect_to new_admin_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def highlight_menu(current_menu, menu)
    current_menu == menu ? 'am-active' : ''
  end

  def website_title
    return '中华家圆' if @title.nil?
    return "#{@title}"
  end
  def controller?(*controller)
    controller.include?(params[:controller])
  end

  def action?(*action)
    action.include?(params[:action])
  end
end

app/helpers/custom_form_helper.rb
module CustomFormHelper
  def custom_form_for(object, *args, &block)
    options = args.extract_options!
    simple_form_for(object, *(args << options.merge(builder: CustomFormBuilder)), &block)
  end

  class CustomFormBuilder < SimpleForm::FormBuilder
    def input(attribute_name, options = {}, &block)
      super(attribute_name, options.reverse_merge(label: false, wrapper: false, input_html: { class: 'form-control' }), &block)
    end
  end

  def link_to_add_my_fields(name)
    fields = render("product_attribute_definition_fields")
    link_to(name, "javascript:add_fields(this, \"#{escape_javascript(fields)}\")")
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/product_images_helper.rb
module ProductImagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admins/_form.html.erb
<div class="row">
  <div class="col-md-12">
  <%= custom_form_for @admin, html: { class: 'form-horizontal' } do |f| %>
  <div class="panel">
    <div class="panel-body">
      <div class="form-group">
        <label class="col-md-3 control-label">Email*</label>
        <div class="col-md-7">
          <%= f.input :email, as: :string, required: true %>
        </div>
      </div>

      <% if @admin.new_record? %>
        <div class="form-group">
          <label class="col-md-3 control-label">密码*</label>
          <div class="col-md-7">
            <%= f.input :password, as: :string, required: true %>
          </div>
        </div>

        <div class="form-group">
          <label class="col-md-3 control-label">确认密码*</label>
          <div class="col-md-7">
            <%= f.input :password_confirmation, as: :string, required: true %>
          </div>
        </div>
    <% end %>
    </div>
    <div class="panel-footer text-center">
      <button type="submit" class="mb-sm btn btn-primary">提交</button>
    </div>
  </div>
  <% end %>

  </div>
</div>

app/views/admins/edit.html.erb
<div class="page-wrapper-row full-height">
  <div class="page-wrapper-middle">
    <div class="page-container">
      <div class="page-content-wrapper">
        <div class="page-head">
          <div class="container">
            <div class="page-title">
              <h1>账号管理</h1>
            </div>
          </div>
        </div>
        <div class="page-content">
          <div class="container">
            <ul class="page-breadcrumb breadcrumb">
              <li>
                  <a href="<%= root_path %>">首页</a>
                  <i class="fa fa-circle"></i>
              </li>
              <li>
                  <a href="javascript:;">账号管理</a>
                  <i class="fa fa-circle"></i>
              </li>
              <li>
                  <span>修改账号信息</span>
              </li>
            </ul>
            <div class="page-content-inner">
              <div class="mt-content-body">
                <div class="row">
                  <div class="portlet light">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="con-list"></i>修改账号信息 </div>
                        <div class="actions">
                            <a href="<%= admins_path %>" class="btn btn-circle btn-info">
                                <i class="glyphicon glyphicon-arrow-left"></i>
                                <span class="hidden-xs"> 返回 </span>
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                      <%= render 'form' %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admins/edit_password.html.erb
<section>
  <div class="content-wrapper border-none">
    <h3 class="paper-title border-none">账号管理
      <small>修改密码</small>
    </h3>
  </div>
  <%= custom_form_for @admin, url: update_password_admin_path(@admin), html: { class: 'form-horizontal', method: :post } do |f| %>
    <input type="hidden" name="return_url" value="<%= params[:return_url] %>">
    <div class="panel">
      <div class="panel-body">
        <div class="form-group">
          <label class="col-md-3 control-label">新密码*</label>
          <div class="col-md-7">
            <%= f.input :password, as: :string, required: true %>
          </div>
        </div>

        <div class="form-group">
          <label class="col-md-3 control-label">确认密码*</label>
          <div class="col-md-7">
            <%= f.input :password_confirmation, as: :string, required: true %>
          </div>
        </div>
      </div>
      <div class="panel-footer text-center">
        <button type="submit" class="mb-sm btn btn-primary">提交</button>
      </div>
    </div>
  <% end %>
</section>

app/views/admins/index.html.erb
<section>
  <div class="content-wrapper border-none">
    <div class="btn-group pull-right">
      <div class="row">
        <a href="<%= new_admin_path %>" class="mb-sm btn btn-primary">
          <i class="fa fa-plus"></i>
          <span class="hidden-xs"> 新增 </span>
        </a>
      </div>
    </div>
    <h3 class="paper-title border-none">账号管理
      <small>账号列表</small>
    </h3>
  </div>
  <div class="panel">
    <table class="table table-bordered table-hover">
      <thead>
        <tr class="table-header">
          <th>用户名</th>
          <th>登录次数</th>
          <th>最后登录时间</th>
          <th>最后登录IP</th>
          <th>操作</th>
        </tr>
       </thead>
       <tbody>
          <% @admins.each do |admin| %>
            <tr>
              <td><%= admin.email %></td>
              <td><%= admin.sign_in_count %></td>
              <td><%= admin.last_sign_in_at.strftime('%Y-%m-%d %H:%M:%S') if admin.last_sign_in_at.present?  %></td>
              <td><%= admin.last_sign_in_ip %></td>
              <td>
                <a href="<%= edit_password_admin_path(admin, return_url: request.url) %>" class="btn btn-primary mb-sm">
                  修改密码
                </a>
              </td>
            </tr>
          <% end %>
       </tbody>
    </table>

    <div id='paginate' class="pagination text-center">
      <%= paginate @admins %>
    </div>
  </div>
</section>

app/views/admins/new.html.erb
<section>
  <div class="content-wrapper border-none">
    <h3 class="paper-title border-none">账号管理
      <small>新增账号</small>
    </h3>
  </div>
  <%= render 'form' %>
</section>

app/views/layouts/application.html.erb
<!doctype html>
<html class="no-js">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta property="wb:webmaster" content="40f26e2fd8bb84c8" />
  <meta name="description" content="">
  <meta name="keywords" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <title>商城后台</title>
  <%= stylesheet_link_tag 'reset' %>
  <%= stylesheet_link_tag 'base' %>
  <%= stylesheet_link_tag 'application'%>
  <%= javascript_include_tag 'application'%>
  <%= javascript_include_tag 'base' %>
  <%= yield :styles %>
  <%= yield :scripts %>
  <%= csrf_meta_tags %>
</head>
<body>
<!--[if lte IE 9]>
<p class="browsehappy">你正在使用<strong>过时</strong>的浏览器。 请 <a
  href="http://browsehappy.com/" target="_blank">升级浏览器</a>
  以获得更好的体验！</p>
<![endif]-->

   <div class="wrapper">
      <header class="topnavbar-wrapper">
         <%= render partial: "layouts/partials/topnavbar" %>
      </header>
      <aside class="aside">
         <%= render partial: "layouts/partials/sidebar" %>
      </aside>
      <section style="background: #fff">
         <div class="content-wrapper">
           <% if flash[:alert].present? %>
             <div class="custom-alerts alert alert-danger fade in">
               <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
               <%= flash[:alert] %>
             </div>
           <% end %>

           <% if flash[:notice].present? %>
             <div class="custom-alerts alert alert-success fade in">
               <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
               <%= flash[:notice] %>
             </div>
           <% end %>
           <%= yield %>
         </div>
      </section>
      <footer>
         <%= render partial: "layouts/partials/footer" %>
      </footer>
   </div>

   <%= yield :body_area %>

</body>
</html>

app/views/layouts/login.html.erb
<!doctype html>
<html class="no-js">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta property="wb:webmaster" content="40f26e2fd8bb84c8" />
  <meta name="description" content="">
  <meta name="keywords" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <title>商城数据管理后台</title>
  <%= stylesheet_link_tag 'reset' %>
  <%= stylesheet_link_tag 'base' %>
  <%= stylesheet_link_tag 'application'%>
  <%= javascript_include_tag 'application'%>
  <%= javascript_include_tag 'base' %>
  <%= yield :styles %>
  <%= yield :scripts %>
  <%= csrf_meta_tags %>
</head>
<body>
<!--[if lte IE 9]>
<p class="browsehappy">你正在使用<strong>过时</strong>的浏览器。 请 <a
  href="http://browsehappy.com/" target="_blank">升级浏览器</a>
  以获得更好的体验！</p>
<![endif]-->
   <div class="wrapper">
      <%= yield %>
   </div>
   <div class="p-lg text-center">
      <span>&copy;</span>
      <span>2017</span>
      <span>-</span>
      <span>商城后台</span>
      <br>
   </div>
</body>
</html>

app/views/layouts/partials/_footer.html.erb
<span>&copy; 2017 - 商城后台</span>

app/views/layouts/partials/_sidebar.html.erb
<div class="aside-inner">
   <nav class="sidebar" data-sidebar-anyclick-close="">
      <ul class="nav">
         <li class="<%= 'active' if controller?('home')%>">
            <a href="<%= root_path %>" title="首页">
               <em class="icon-home"></em>
               <span data-localize="sidebar.nav.DASHBOARD">首页</span>
            </a>
         </li>
         <li class="<%= 'active' if controller?('admins') && action?('index')%>">
            <a href="#admin" title="账户管理" data-toggle="collapse">
               <em class="icon-notebook"></em>
               <span>账户管理</span>
            </a>
            <ul id="admin" class="nav sidebar-subnav collapse">
               <li class="<%= 'active' if controller?('admins') %>">
                  <a href="<%= admins_path %>" title="账户列表">
                     <span>账户列表</span>
                  </a>
               </li>
            </ul>
         </li>
         <li class="<%= 'active' if controller?('products') || controller?('product_categories')%>" >
            <a href="#products" title="商品管理" data-toggle="collapse">
               <em class="icon-people"></em>
               <span>商品管理</span>
            </a>
            <ul id="products" class="nav sidebar-subnav collapse">
               <li class="<%= 'active' if controller?('products') %>">
                  <a href="<%= products_path %>" title="商品列表">
                     <span>商品列表</span>
                  </a>
               </li>
               <li class="<%= 'active' if controller?('product_categories') %>">
                  <a href="<%= product_categories_path %>" title="商品分类">
                     <span>商品分类</span>
                  </a>
               </li>
            </ul>
         </li>
         <li class="<%= 'active' if controller?('customers')%>" >
            <a href="#customer" title="客户管理" data-toggle="collapse">
               <em class="icon-people"></em>
               <span>客户管理</span>
            </a>
            <ul id="customer" class="nav sidebar-subnav collapse">
               <li class="<%= 'active' if controller?('customers') %>">
                  <a href="<%= customers_path %>" title="用户列表">
                     <span>用户列表</span>
                  </a>
               </li>
               <li >
                  <a href="<%= admins_path %>" title="客户批量导入">
                     <span>客户地址列表</span>
                  </a>
               </li>
            </ul>
         </li>
         <li >
            <a href="#orders" title="订单管理" data-toggle="collapse">
               <em class="icon-list"></em>
               <span>订单管理</span>
            </a>
            <ul id="orders" class="nav sidebar-subnav collapse">
               <li >
                  <a href="<%= admins_path %>" title="订单搜索">
                     <span>订单搜索</span>
                  </a>
               </li>
               <li >
                  <a href="<%= admins_path %>" title="支付统计">
                     <span>支付统计</span>
                  </a>
               </li>
            </ul>
         </li>
         <li >
            <a href="#feed_back" title="反馈信息管理" data-toggle="collapse">
               <em class="icon-bubble"></em>
               <span>反馈信息管理</span>
            </a>
            <ul id="feed_back" class="nav sidebar-subnav collapse">
               <li >
                  <a href="<%= admins_path %>" title="投诉办理">
                     <span>投诉办理</span>
                  </a>
               </li>
               <li >
                  <a href="<%= admins_path %>" title="反馈建议">
                     <span>反馈建议</span>
                  </a>
               </li>
               <li >
                  <a href="<%= admins_path %>" title="评价管理">
                     <span>评价管理</span>
                  </a>
               </li>
            </ul>
         </li>
         <li >
            <a href="#settings" title="系统设置" data-toggle="collapse">
               <em class="icon-settings"></em>
               <span>系统设置</span>
            </a>
            <ul id="settings" class="nav sidebar-subnav collapse">
               <li >
                  <a href="<%= admins_path %>" title="等级规则设置">
                     <span>等级规则设置</span>
                  </a>
               </li>
               <li >
                  <a href="<%= admins_path %>" title="积分规则设置">
                     <span>积分规则设置</span>
                  </a>
               </li>
               <li >
                  <a href="<%= admins_path %>" title="api列表">
                     <span>api列表</span>
                  </a>
               </li>

            </ul>
         </li>
<!--          <li class="nav-heading">
            <span>More</span>
         </li>
 -->
      </ul>
   </nav>
</div>

app/views/layouts/partials/_topnavbar.html.erb
<nav role="navigation" class="navbar topnavbar">
   <div class="navbar-header">
      <a href="<%= root_path %>" class="navbar-brand">
         <div class="brand-logo">
            <span style="color: white">商城后台</span>
         </div>
         <div class="brand-logo-collapsed">
         </div>
      </a>
   </div>
   <div class="nav-wrapper">
      <ul class="nav navbar-nav">
         <li>
            <a href="#" data-trigger-resize="" data-toggle-state="aside-collapsed" class="hidden-xs">
               <em class="fa fa-navicon"></em>
            </a>
            <a href="#" data-toggle-state="aside-toggled" data-no-persist="true" class="visible-xs sidebar-toggle">
               <em class="fa fa-navicon"></em>
            </a>
         </li>
      </ul>
      <!-- END Left navbar-->
      <!-- START Right Navbar-->
      <ul class="nav navbar-nav navbar-right">
         <!-- START Alert menu-->
         <li class="dropdown dropdown-list">
            <a href="#" data-toggle="dropdown">
               <em class="icon-bell"></em>
               <div class="label label-danger">0</div>
            </a>
            <ul class="dropdown-menu animated flipInX">
               <li>
                  <div class="list-group">
                     <a href="#" class="list-group-item">
                        <div class="media-box">
                           <div class="pull-left">
                              <em class="fa fa-envelope fa-2x text-warning"></em>
                           </div>
                           <div class="media-box-body clearfix">
                              <p class="m0">新邮件</p>
                              <p class="m0 text-muted">
                                 <small>0</small>
                              </p>
                           </div>
                        </div>
                     </a>
                     <a href="#" class="list-group-item">
                        <div class="media-box">
                           <div class="pull-left">
                              <em class="fa fa-tasks fa-2x text-success"></em>
                           </div>
                           <div class="media-box-body clearfix">
                              <p class="m0">新任务</p>
                              <p class="m0 text-muted">
                                 <small>0</small>
                              </p>
                           </div>
                        </div>
                     </a>
                  </div>
               </li>
            </ul>
         </li>
         <li class="dropdown dropdown-list">
            <a href="#" data-toggle="dropdown">
               <em class="icon-user"></em>
            </a>
            <ul class="dropdown-menu  animated bounceIn">
               <li>
                  <div class="list-group-cn-height">
                     <a href="<%= edit_password_admin_path(current_admin) %>" class="list-group-item">
                        <div class="media-box">
                           <div class="pull-left">
                              <em class="fa fa-edit fa-2x text-success"></em>
                           </div>
                           <div class="media-box-body clearfix">
                              <p class="m0 text-center">修改密码</p>
                           </div>
                        </div>
                     </a>
                     <a href="<%= destroy_admin_session_path %>" data-method="delete" data-confirm="确认注销登录吗？" class="list-group-item">
                        <div class="media-box">
                           <div class="pull-left">
                              <em class="fa fa-sign-out fa-2x text-success"></em>
                           </div>
                           <div class="media-box-body clearfix">
                              <p class="m0 text-center">注销登录</p>
                           </div>
                        </div>
                     </a>
                  </div>
               </li>
            </ul>
         </li>
      </ul>
   </div>
</nav>