config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: { sessions: 'sessions' }, skip: [:registrations, :passwords]
  root to: 'home#index'
  resources :home, only: [:index]
  resources :products
  resources :product_categories
  resources :product_images
  resources :customers
  resources :orders
  resources :order_items
  resources :admins do
    member do
      get :edit_password
      post :update_password
    end
  end

  get '*path' => redirect('/')
end

app/models/customer.rb
# == Schema Information
#
# Table name: customers
#
#  id         :integer          not null, primary key
#  nickname   :string(191)
#  mobile     :string(191)
#  password   :string(191)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Customer < ApplicationRecord
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customer = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def new
    @customer = Customer.new
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def create
    @customer = Customer.new(products_params)
    if @customer.save
      redirect_to customers_path
    else
      render :new
    end
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(products_params)
      redirect_to @customer
    else
      render 'edit'
    end
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    redirect_to customers_path
  end

  private
    def products_params
      params.require(:customer).permit!
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/edit.html.erb
<div class="content-heading">
  商品内容修改
</div>
<div class="row">
  <%= form_for @customer do |f| %>
  <p>
    <%= f.label :修改密码： %>
    <%= f.text_field :password %>
  </p>
  <p>
    <button type="submit" class="btn btn-primary">完成修改</button>
  </p>
  <% end %>
</div>

app/views/customers/index.html.erb
<div class="content-heading">
   <div class="pull-right">
      <div class="btn-group">
         <button type="button" class="btn"><%= link_to '新增用户', new_customer_path %></button>
      </div>
   </div>
   用户列表
</div>
<!-- START widgets box-->
<div class="row">
   <table class="table table-bordered">
      <tr>
         <th>用户id</th>
         <th>用户昵称</th>
         <th>用户电话</th>
         <th>用户密码</th>
         <th>操作</th>
      </tr>
      <% @customer.each do |customer| %>
      <tr>
         <td><%= customer.id %></td>
         <td><%= customer.nickname %></td>
         <td><%= customer.mobile %></td>
         <td><%= customer.password %></td>
         <td><%= link_to '查看', customer_path(customer) %>|<%= link_to '删除' %></td>
      </tr>
      <% end %>
   </table>
</div>

app/views/customers/show.html.erb
<div class="content-heading">
   <div class="pull-right">
      <div class="btn-group">
      <button type="button" class="btn"><%= link_to "修改密码",edit_customer_path(@customer) %></button>
        <button type="button" class="btn"><%= link_to "返回",customers_path %></button>
      </div>
   </div>
  用户详情
</div>
<div class="row">
  <p class="bg-primary"><strong>用户id:</strong>&nbsp&nbsp<%= @customer.id %></p>
  <p class="bg-success"><strong>用户昵称:</strong>&nbsp&nbsp<%= @customer.nickname %></p>
  <p class="bg-info"><strong>用户头像：</strong>&nbsp&nbsp<img src="/assets/angle/user/02.jpg" class="img-rounded"></p>  
  <p class="bg-warning"><strong>用户账号:</strong>&nbsp&nbsp<%= @customer.mobile %></p>
  <p class="bg-success"><strong>用户收货地址：</strong></p>
  <p class="bg-primary"><strong>用户订单数：</strong></p>
</div>