config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: { sessions: 'sessions' }, skip: [:registrations, :passwords]
  root to: 'home#index'
  resources :home, only: [:index]
  resources :products
  resources :product_categories
  resources :product_images
  resources :customers
  resources :orders
  resources :order_items
  resources :admins do
    member do
      get :edit_password
      post :update_password
    end
  end

  get '*path' => redirect('/')
end

app/models/product_category.rb
# == Schema Information
#
# Table name: product_categories
#
#  id         :integer          not null, primary key
#  name       :string(191)
#  comment    :string(191)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class ProductCategory < ApplicationRecord
  has_many :products
end

app/controllers/product_categories_controller.rb
class ProductCategoriesController < ApplicationController
  protect_from_forgery with: :exception
  def index
    @productCategory = ProductCategory.all
  end

  def new
    @product_category = ProductCategory.new
  end
  def create
    @product_category = ProductCategory.new(product_category_params)

    if @product_category.save
      redirect_to product_categories_path
    else
      render :new
    end
  end

  def destroy
    @productCategory = ProductCategory.find(params[:id])
    @productCategory.destroy
    redirect_to product_categories_path
  end

  private
    def product_category_params
      params.require(:product_category).permit!
    end
end

app/helpers/productcategories_helper.rb
module ProductcategoriesHelper
end

app/views/product_categories/index.html.erb
<div class="content-heading">
   <div class="pull-right">
      <div class="btn-group">
         <button type="button" class="btn"><%= link_to '新增商品分类', new_product_category_path %></button>
      </div>
   </div>
   商品列表
</div>
<div class="row">
   <table class="table table-bordered">
      <tr>
         <th>id</th>
         <th>商品分类名称</th>
         <th>备注</th>
         <th>操作</th>
      </tr>
   <% @productCategory.each do |productcategory| %>   
      <tr>
         <td><%= productcategory.id %></td>
         <td><%= productcategory.name %></td>
         <td><%= productcategory.comment %></td>
         <td><%= link_to '删除', product_category_path(productcategory), method: :delete  %></td>
      </tr>
   <% end %>
   </table>
</div>

app/views/product_categories/new.html.erb
<div class="content-heading">
   <div class="pull-right">
      <div class="btn-group">
         <button type="button" class="btn"><%= link_to '返回', product_categories_path %></button>
      </div>
   </div>
   新增商品分类
</div>
<div class="row">
  <%= form_for @product_category do |f| %>
  <p>
    <%= f.label :商品分类id： %>
    <%= f.text_field :id %>
  </p>
  <p>
    <%= f.label :商品分类名称： %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :备注： %>
    <%= f.text_field :comment %>
  </p>

  <p>
    <button type="submit" class="btn btn-primary">添加完成</button>
  </p>
  <% end %>

</div>